### ISSUE TITLE
Error in Compiling

### ISSUE THREAD

**Issue by DemonRem** [haversine-air/AirPlugin#14]
Dear Haversine Team, 

I try to compile the project but I have a error

> C:\Users\Nayla\Documents\GitHub\AirPlugin>make win64
/usr/local/mingw-w64-bin_i686-darwin_20130622/bin/x86_64-w64-mingw32-gcc -o HaversineAir/64/win.xpl ./source/hsxplclist.c ./source/hsxpl.c      ./source/hsxplmcp.c ./source/hsxplcoms.c ./HSMP/hsmpnet.c ./HSMP/hsmptcp.c ./source/hsxplcpflight.c ./source/hsxplmisc.c ./source/hsxplnavdb.c ./source/hsxplatc.c ./source/hsxplairports.c ./source/hsxpldref-requests.c ./source/hsxpldefault738.c ./source/hsxplzibo738.c ./source/hsxplfmc.c ./source/hsxplsettings.c ./source/hsxpleadtx738.c ./source/hsxplixeg733.c ./source/hsxpljara320.c ./source/hsxpldatarefs.c source/hsxplff757.c ./source/hsxplff767.c ./source/hsxplff777.c ./source/hsxplcrj200.c ./source/hsxplxfmc.c ./source/hsxplufmc.c ./source/hsxplqa320.c ./source/hsxplxsquawkbox.c -DCPFXPL=1 -DXPLM200=1 -DXPLM210=1 -DXPLM211=1 -DXPL=1 -DCPFLIGHT=1 -Wunused-function -Wunused-label -Wunused-value -Wunused-variable -Wimplicit-function-declaration  -DIBM=1 -DAPL=0 -DLIN=0 -D_WIN32=1 -DCPFLIGHT=1 -I. -I.. -I./XPSDK/CHeaders/XPLM -I./XPSDK/CHeaders/Widgets -I./HSMP   -m64 -shared -L ./XPSDK/Libraries/Win  -lXPLM_64 -lXPWidgets_64 -lws2_32
process_begin: CreateProcess(NULL, /usr/local/mingw-w64-bin_i686-darwin_20130622/bin/x86_64-w64-mingw32-gcc -o HaversineAir/64/win.xpl ./source/hsxplclist.c ./source/hsxpl.c ./source/hsxplmcp.c ./source/hsxplcoms.c ./HSMP/hsmpnet.c ./HSMP/hsmptcp.c ./source/hsxplcpflight.c ./source/hsxplmisc.c ./source/hsxplnavdb.c ./source/hsxplatc.c ./source/hsxplairports.c ./source/hsxpldref-requests.c ./source/hsxpldefault738.c ./source/hsxplzibo738.c ./source/hsxplfmc.c ./source/hsxplsettings.c ./source/hsxpleadtx738.c ./source/hsxplixeg733.c ./source/hsxpljara320.c ./source/hsxpldatarefs.c source/hsxplff757.c ./source/hsxplff767.c ./source/hsxplff777.c ./source/hsxplcrj200.c ./source/hsxplxfmc.c ./source/hsxplufmc.c ./source/hsxplqa320.c ./source/hsxplxsquawkbox.c -DCPFXPL=1 -DXPLM200=1 -DXPLM210=1 -DXPLM211=1 -DXPL=1 -DCPFLIGHT=1 -Wunused-function -Wunused-label -Wunused-value -Wunused-variable -Wimplicit-function-declaration -DIBM=1 -DAPL=0 -DLIN=0 -D_WIN32=1 -DCPFLIGHT=1 -I. -I.. -I./XPSDK/CHeaders/XPLM -I./XPSDK/CHeaders/Widgets -I./HSMP -m64 -shared -L ./XPSDK/Libraries/Win -lXPLM_64 -lXPWidgets_64 -lws2_32, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [HaversineAir/64/win.xpl] Error 2

**Comment by jonvcb** [comment]
The included makefile uses a cross compile of MinGW for MacOS when compiling for Windows which will for sure not work on Windows itself. 

You can either try it with another compiler such as Microsoft Visual C but you'll need to create another makefile or build file for it, or you can try and install MinGW from:

http://www.mingw.org

And adjust the makefile for it. Again I've never done this on windows itself but it should be the best option. Edit the makefile and replace the line that says CCWIN32=... to have the right compiler location. 

Alternatively if you've some changes I can try and build them for you here on a mac. 

Sorry for the trouble, 
joao
