### ISSUE TITLE
 contributor Premission

### ISSUE THREAD

**Issue by DemonRem** [haversine-air/AirPlugin#17]
@jonvcb 
can you add me as contributor to the project?

**Comment by jonvcb** [comment]
I think I just did, let me know if you have any trouble submitting a PR.

**Comment by DemonRem** [comment]
ok

**Comment by DemonRem** [comment]
no i dont have premission yet

**Comment by jonvcb** [comment]
Sorry, I'm not really very familiar with github. 

Apparently it's waiting for you to accept the invite. 

Try going to: https://github.com/haversine-air/AirPlugin/invitations

And see it there is something you can press to accept it.

**Comment by DemonRem** [comment]
thank
